services:
    account_manager.default:
        class: YV\MultiCurrencyBundle\Model\ModelManager\AccountManager
        arguments: [ @doctrine.orm.entity_manager, @event_dispatcher, %yv_multi_currency.account_class% ]
    
    currency_manager.default:
        class: YV\MultiCurrencyBundle\Model\ModelManager\CurrencyManager
        arguments: [ @doctrine.orm.entity_manager, @event_dispatcher, %yv_multi_currency.currency_class% ]
    
    currency_account_manager.default:
        class: YV\MultiCurrencyBundle\Model\ModelManager\CurrencyAccountManager
        arguments: [ @doctrine.orm.entity_manager, @event_dispatcher, %yv_multi_currency.currency_account_class% ]
    
    transaction_manager.default:
        class: YV\MultiCurrencyBundle\Model\ModelManager\TransactionManager
        arguments: [ @doctrine.orm.entity_manager, @event_dispatcher, %yv_multi_currency.transaction_class% ]