imports:
    - { resource: managers.yml }

services:
    chains.manager_chain:
        class: YV\MultiCurrencyBundle\Lib\Chain\ManagerChain     
        
    # Listeners 
    currency_listener.default:
        class: YV\MultiCurrencyBundle\Listener\CurrencyListener
        arguments: [@chains.manager_chain]
        tags:
            - { name: kernel.event_listener, event: yv_multi_currency.change_amount, method: onChangeAmount }
            - { name: kernel.event_listener, event: yv_multi_currency.delete_currency, method: onDeleteCurrency }
            - { name: kernel.event_listener, event: yv_multi_currency.add_currency, method: onAddCurrency }
    
    doctrine.file_upload_listener:
        class:     YV\MultiCurrencyBundle\Listener\FileUploadListener
        arguments: [ %kernel.file_upload_dir%, %kernel.file_upload_root_dir% ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate } 
            - { name: doctrine.event_listener, event: postLoad }